# Favicon
#favicon: /favicon.ico
favicon: /images/puffin.png

# SEO
keywords: Mathematica,C++,C,Linux,Qt,WebRTC

# Site title separator
separator: '-'

# RSS
rss: /atom.xml

# SNS config
sns:
  Blog: /archives
  Public: /public
  About: /about

# Nav menu
menu:
  Blog: /archives
  Public: /folders
  Links: /links
  About: /about

